# SSH null host keys
How to deal with a machine whose hostkey keeps changing (from reinstalls etc)

    host localhost
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null

* user demo to alice *
