# history tricks
##histcontrol
* control what goes into your history file
##histignore
* ignore more fine grained
##histsearch
* "what was that command?"
##histverify
* "I want to re-run that command but a little different"
##fc
* "oh man I really messed up, I need to edit that command in my $EDITOR"

