# mac tips

## open
Smart opening of almost any type of file.

## hdiutil
Command-line disk image managment.

## drutil
CD drive management

## say
Text to speech

## oascript
Apple scripting -- WAY POWERFUL 

## pbcopy/pbpaste
Send your clipboard through a pipe.

## airport
Find the binary and put it in your PATH. Wireless management.

## mdtools(IIRC)
Spotlight for your shell

