# some best practices for bash scripting

## Variables
Always this form

    ${FOO}

## Quoting
Always quote unless you know what you're doing

    echo "${FOO}"

## Dealing with dashes
if FOO starts with "-e" it's passed to echo as a switch

    echo -- "${FOO}"

