# useful aliases

* `q='exit'` 
* `ll='ls -l'`
* `la='ls -la'`
* `ls='ls --color=auto -F'`
* `redo='sudo !!'`
* `please=''`
* `thanks='echo no prob'`
* `realias='source ${HOME}/.bash_aliases'`
* `refunction='source ${HOME}/.bash_functions'`

