# default keybindings

* `ctrl-x ctrl-e` -- edit the current command using $EDITOR
* `ctrl-d` -- End of File (EOF) -- used to exit bash if properly setup
* `esc .` -- NOTE: not a cord, should be entered as two keystrokes insert the previous command's last argument at the cursor position (cycles back through your history)
* `ctrl-a` -- move to front of line
* `ctrl-e` -- move to end of line
* `ctrl-t / alt-t` -- transpose chars/words
* `alt-u` -- uppercase a word at a time
* `ctrl-u` -- erase from cursor to beginning of line
* `ctrl-r` -- search backwords through history interactively
