# Your favorite text tools

## Cat/Tac
Useful for spilling the contents of a file.

### tricks
    cat -A
    tac # goes backwords

### movie
* demo goes here *

## head/tail
Useful for seeing the top/bottom of a file.

### tricks

    head -n 3 # show top three lines
    tail -f # watch and "FOLLOW" a file in real-time

### movie
* demo goes here *

## tr
"Translate" a character

### tricks

    echo "one   really long   string" | tr -s ' ' # "squeeze" the spaces

## cut 
Slice up a sub-string lots of fun.

### tricks

* `-c` -- character based cuts
* `-f` -- field based cuts (use with `-d`)
* `-d` -- the delimiter

## paste
Serialize related data

* demo goes here *
